networks:
  app-tier:
    driver: bridge

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-nyc-taxi
    hostname: kafka-nyc-taxi
    networks:
      - app-tier
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-nyc-taxi:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-nyc-taxi:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  materialized:
    image: materialize/materialized:latest
    container_name: materialize-nyc-taxi
    networks:
      - app-tier
    ports:
      - "127.0.0.1:6874:6874"
      - "127.0.0.1:6875:6875"
      - "127.0.0.1:6876:6876"